### 표본의 평균 검정


#### 모집단의 분산(표준편차)을 알고 있는 경우
* Z-test(양측)

In [8]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import norm

data = np.array([23,25,28,30,26,27,29,32,31,28])

In [11]:
모평균 = 28
모분산 = 4

유의수준 = 0.05

alternative = "two.sided"

n = len(data)

sample_mean = np.mean(data)

# 검정통계량 계산
test_statistics = (sample_mean - 모평균) / (np.sqrt(모분산) / np.sqrt(n))

# 임계값 계산
critical_value = norm.ppf(1 - 유의수준 / 2)

# p-값 계산
p_value = 2*(1-norm.cdf(abs(test_statistics)))

print(test_statistics)
print(critical_value)
print(p_value)

-0.15811388300842122
1.959963984540054
0.87436706116289


* 분산을 모를 때


In [19]:
alpha = 0.05
alternative = 'two-sided'

# t 검정 수행 , 단일표본검정을 할 수 있는 함수사용
t_statistics, p_value = stats.ttest_1samp(data, popmean = 0, alternative = alternative)

# 95% 신뢰 구간 계산
confidence_interval = stats.t.interval(1-alpha, len(data)-1, loc=np.mean(data),scale = stats.sem(data))

print(t_statistics)
print(p_value)
print(confidence_interval)



31.887160448233363
1.4410218033665443e-10
(25.92070225277866, 29.879297747221337)


In [20]:
## 따라하기 예제

import pandas as pd
import numpy as np
from scipy import stats

mtcars = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/mtcars.csv')

In [21]:
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [23]:
# mpg 데이터에 대한 표본 평균 구하기
mpg_mean = round(np.mean(mtcars['mpg']),4)

print(mpg_mean)


20.0906


In [41]:
# mpg 데이터에 대한 표본 분산구하기
mpg_std = round(np.var(mtcars['mpg'], ddof = 1),4)

print(mpg_std)

35.189


In [42]:
# mpg의 평균이 20이라는 가설 검정
## 모분산을 모르므로 t검정

t_statistics, p_value = stats.ttest_1samp(mtcars['mpg'], popmean = 20, alternative='two-sided')

print(t_statistics, p_value)

# 귀무가설 기각불가

0.08506003568133688 0.9327606409093872


In [40]:
# 95% 신뢰구간 계산
alpha = 0.05
confidence_interval = stats.t.interval(1-alpha,len(mtcars['mpg'])-1, loc = mpg_mean, scale = stats.sem(mtcars['mpg']))

print(confidence_interval)

(17.91765350874624, 22.263546491253756)


In [37]:
help(stats.t.interval)

Help on method interval in module scipy.stats._distn_infrastructure:

interval(confidence, *args, **kwds) method of scipy.stats._continuous_distns.t_gen instance
    Confidence interval with equal areas around the median.
    
    Parameters
    ----------
    confidence : array_like of float
        Probability that an rv will be drawn from the returned range.
        Each value should be in the range [0, 1].
    arg1, arg2, ... : array_like
        The shape parameter(s) for the distribution (see docstring of the
        instance object for more information).
    loc : array_like, optional
        location parameter, Default is 0.
    scale : array_like, optional
        scale parameter, Default is 1.
    
    Returns
    -------
    a, b : ndarray of float
        end-points of range that contain ``100 * alpha %`` of the rv's
        possible values.
    
    Notes
    -----
    This is implemented as ``ppf([p_tail, 1-p_tail])``, where
    ``ppf`` is the inverse cumulative distribut

#### 두 독립표본의 평균, 중앙값 차이 검정

T 검정 - 정규성을 가정

In [44]:
from scipy.stats import stats

sample1 = [23,25,28,30,32]
sample2 = [19,21,24,26,29]


In [47]:
p_value = stats.ttest_ind(sample1, sample2)

print(p_value)

TtestResult(statistic=1.5778641172210597, pvalue=0.15324889402868613, df=8.0)


<ipython-input-47-e796bcb67042>:1: DeprecationWarning: Please use `ttest_ind` from the `scipy.stats` namespace, the `scipy.stats.stats` namespace is deprecated.
  p_value = stats.ttest_ind(sample1, sample2)


맨휘트니검정- 정규성 가정 x, 중앙값 비교

In [52]:
from scipy import stats

u_statistics, p_value = stats.mannwhitneyu(sample1, sample2)

print(p_value)

0.2222222222222222


정규성 검정 : 분포가 정규분포인지 확인
* 샤피로-윌크 검정




In [55]:
data = [2.4, 2.7, 3.1, 3.2, 3.5, 3.7, 3.9, 4.1, 4.2]

statistics, p_value = stats.shapiro(data)

print(p_value)

0.7484778761863708


따라하기


In [62]:
# 각각의 샘플의 평균 구하기
dat_M = [117, 108, 105, 89, 101, 93, 96, 108, 108, 94, 93, 112, 92, 91, 100, 96, 120, 86, 96, 95]
dat_F = [121, 101, 102, 114, 103, 105, 101, 131, 96, 109, 109, 113, 115, 94, 108, 96, 110, 112, 120, 100]

mean_M = np.mean(dat_M)
mean_F = np.mean(dat_F)

print(mean_M)
print(mean_F)

100.0
108.0


In [70]:
# 각 샘플에 대해 정규성 검정 수행

stat1, p1 = stats.shapiro(dat_M)
stat2, p2 = stats.shapiro(dat_F)

print(p1)
print(p2)

# 두 개 모두 정규분포를 따른다.

t_statistics, p_value = stats.ttest_ind(dat_M, dat_F)

print(p_value)

0.17352384328842163
0.5747838020324707
0.011082895240510138


In [ ]:
dir(stats)

#### 대응 표본 평균 차이 검정


In [ ]:
before = [7, 3, 4, 5, 2, 1, 6, 6, 5, 4]
after = [8, 4, 5, 6, 2, 3, 6 ,8 , 6, 5]

In [74]:
# 정규성검정
p1 = stats.shapiro(before)
p2 = stats.shapiro(after)

print(p1, p2)

# 정규분포를 따른다.

ShapiroResult(statistic=0.9644591808319092, pvalue=0.835266649723053) ShapiroResult(statistic=0.945683479309082, pvalue=0.6177965998649597)


In [76]:
# t test를 통한 평균 대응표본 비교 (related)

t1, p_1 = stats.ttest_rel(before, after)

print(t1, p_1)

-4.743416490252569 0.0010538712570165528


#### 단일표본 모분산 검정(카이제곱검정)

In [79]:
import numpy as np
from scipy.stats import chi2

data = np.array([14.2, 15.1, 14.8, 15.4, 14.9, 15.2, 14.6, 15.0])

# 가설 모분산은 1과같다. 아니다.

pop_var = 1.0

# 검정통계량 = (n-1) * 표본분산 / 모분산

chi2_statistics = len(data) -1 * np.var(data) / pop_var

degrees_of_freedom = len(data)-1

p_value = 1 - chi2.cdf(chi2_statistics, degrees_of_freedom)

print(p_value)

0.34351977391379007


#### 모분산 비에 대한 검정 : 분산이 동일한지 검정


In [80]:
np.random.seed(123)
sample1 = np.random.normal(loc =5, scale=2, size =50)
sample2 = np.random.normal(loc=5, scale=3, size = 50)

In [81]:
# 각표본의 분산 계산
var1 = np.var(sample1)
var2 = np.var(sample2)

In [83]:
# f검정 통계량 : var1/var2

f = var1 / var2

# f검정실시
p_value = 1-stats.f.cdf(f, len(sample1)-1,len(sample2)-1)

print(p_value)

0.9786532588205227


#### 독립성 검정 (카이제곱 검정) : 주로 범주형 데이터에 대한 통계적 가설검정

In [84]:
from scipy.stats import chi2_contingency

data_matrix = np.array([[50, 75, 125, 175], [90, 30, 45, 10]])

In [89]:
chi2, p, df, expected = chi2_contingency(data_matrix)

print(chi2, p , df ,expected)

134.7511341579557 5.117490956087995e-29 3 [[ 99.16666667  74.375      120.41666667 131.04166667]
 [ 40.83333333  30.625       49.58333333  53.95833333]]


[[ 50  75 125 175]
 [ 90  30  45  10]]


* 따라하기


In [95]:
from scipy.stats import chi2_contingency


df = pd.read_csv('https://raw.githubusercontent.com/YoungjinBD/dataset/main/titanic.csv')

In [96]:
# 교차표 생성

cross_table = pd.crosstab(df['Sex'], df['Survived'])


In [98]:
# 독립성 검정 실시
chi2_contingency(cross_table)

Chi2ContingencyResult(statistic=260.71702016732104, pvalue=1.1973570627755645e-58, dof=1, expected_freq=array([[193.47474747, 120.52525253],
       [355.52525253, 221.47474747]]))

In [102]:
def cal(Age):
  if Age < 20:
    return '10대'
  elif Age < 30:
    return '20대'
  elif Age < 40:
    return '30대'
  elif Age < 50:
    return '40대'
  elif Age < 60:
    return '50대'
  else :
    return '60대'

In [107]:
# Age가 결측인 경우 평균값으로 대체
mean_age = df['Age'].mean()
df['Age'].fillna(mean_age, inplace =True)

In [109]:
# 새로운 열 생성
df['Age_c'] = df['Age'].apply(cal)

In [110]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked Age_c  
0      0         A/5 21171   7.2500   NaN        S   20대  
1      0          PC 17599  71.2833   C85        C   30대  
2      0  STON/O2. 3101282   7.9250   NaN        S   20대  
3      0            113803  53.1000  C123        S   30대  
4      0            373450   8.0500   NaN        S   30대

In [114]:
# 교차표 생성
cross_table = pd.crosstab(df['Survived'], df['Age_c'])

# 검정
chi2_contingency(cross_table)

# 귀무가설 기각, 연령대에 따른 생존여부에 차이가 잇음

Chi2ContingencyResult(statistic=16.134525241016338, pvalue=0.006470311249228111, dof=5, expected_freq=array([[101.05050505, 244.61616162, 102.8989899 ,  54.83838384,
         29.57575758,  16.02020202],
       [ 62.94949495, 152.38383838,  64.1010101 ,  34.16161616,
         18.42424242,   9.97979798]]))